In [1]:
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:/Users/rinop/Downloads/crop_yield.csv")

In [4]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [5]:
df.tail

<bound method NDFrame.tail of                 Crop  Crop_Year       Season              State      Area  \
0           Arecanut       1997  Whole Year               Assam   73814.0
1          Arhar/Tur       1997  Kharif                   Assam    6637.0
2        Castor seed       1997  Kharif                   Assam     796.0
3           Coconut        1997  Whole Year               Assam   19656.0
4       Cotton(lint)       1997  Kharif                   Assam    1739.0
...              ...        ...          ...                ...       ...
19684  Small millets       1998  Kharif                Nagaland    4000.0
19685          Wheat       1998  Rabi                  Nagaland    1000.0
19686          Maize       1997  Kharif       Jammu and Kashmir  310883.0
19687           Rice       1997  Kharif       Jammu and Kashmir  275746.0
19688          Wheat       1997  Rabi         Jammu and Kashmir  239344.0

       Production  Annual_Rainfall   Fertilizer  Pesticide        Yield
0           56708           2051.4   7024878.38   22882.34     0.796087
1            4685           2051.4    631643.29    2057.47     0.710435
2              22           2051.4     75755.32     246.76     0.238333
3       126905000           2051.4   1870661.52    6093.36  5238.051739
4             794           2051.4    165500.63     539.09     0.420909
...           ...              ...          ...        ...          ...
19684        2000           1498.0    395200.00    1160.00     0.500000
19685        3000           1498.0     98800.00     290.00     3.000000
19686      440900           1356.2  29586735.11   96373.73     1.285000
19687        5488           1356.2  26242746.82   85481.26     0.016667
19688      392160           1356.2  22778368.48   74196.64     1.261818

[19689 rows x 10 columns]>

In [6]:
df.size

196890

In [7]:
df.shape

(19689, 10)

In [8]:
df.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='str')

In [9]:
df.isnull().sum

<bound method DataFrame.sum of         Crop  Crop_Year  Season  State   Area  Production  Annual_Rainfall  \
0      False      False   False  False  False       False            False
1      False      False   False  False  False       False            False
2      False      False   False  False  False       False            False
3      False      False   False  False  False       False            False
4      False      False   False  False  False       False            False
...      ...        ...     ...    ...    ...         ...              ...
19684  False      False   False  False  False       False            False
19685  False      False   False  False  False       False            False
19686  False      False   False  False  False       False            False
19687  False      False   False  False  False       False            False
19688  False      False   False  False  False       False            False

       Fertilizer  Pesticide  Yield
0           False      False  False
1           False      False  False
2           False      False  False
3           False      False  False
4           False      False  False
...           ...        ...    ...
19684       False      False  False
19685       False      False  False
19686       False      False  False
19687       False      False  False
19688       False      False  False

[19689 rows x 10 columns]>

In [10]:
df.fillna(df.mean(numeric_only=True), inplace=True)

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909
...,...,...,...,...,...,...,...,...,...,...
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [11]:
df.drop_duplicates(inplace=True)

In [14]:
df["Crop_Year"] = pd.to_datetime(
    df["Crop_Year"],
    format="%Y",
    errors="coerce"
)

In [15]:
df.dtypes

Crop                          str
Crop_Year          datetime64[us]
Season                        str
State                         str
Area                      float64
Production                  int64
Annual_Rainfall           float64
Fertilizer                float64
Pesticide                 float64
Yield                     float64
dtype: object

In [16]:
df.loc[0:5, ["Crop_Year", "Area", "Production"]]

   Crop_Year     Area  Production
0 1997-01-01  73814.0       56708
1 1997-01-01   6637.0        4685
2 1997-01-01    796.0          22
3 1997-01-01  19656.0   126905000
4 1997-01-01   1739.0         794
5 1997-01-01  13587.0        9073

In [17]:
df.iloc[0:5, 0:3]

           Crop  Crop_Year       Season
0      Arecanut 1997-01-01  Whole Year
1     Arhar/Tur 1997-01-01  Kharif
2   Castor seed 1997-01-01  Kharif
3      Coconut  1997-01-01  Whole Year
4  Cotton(lint) 1997-01-01  Kharif

In [18]:
df[df["Area"] > 1000]
df[df["Production"] > 5000]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
5,Dry chillies,1997-01-01,Whole Year,Assam,13587.0,9073,2051.4,1293074.79,4211.97,0.643636
7,Jute,1997-01-01,Kharif,Assam,94520.0,904095,2051.4,8995468.40,29301.20,9.919565
8,Linseed,1997-01-01,Rabi,Assam,10098.0,5158,2051.4,961026.66,3130.38,0.461364
...,...,...,...,...,...,...,...,...,...,...
19682,Maize,1998-01-01,Kharif,Nagaland,30000.0,37000,1498.0,2964000.00,8700.00,1.225714
19683,Rice,1998-01-01,Kharif,Nagaland,141000.0,205000,1498.0,13930800.00,40890.00,1.441429
19686,Maize,1997-01-01,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997-01-01,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997-01-01,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [19]:
df["Production_per_Area"] = df["Production"] / df["Area"]

In [20]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891
2,Castor seed,1997-01-01,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331
4,Cotton(lint),1997-01-01,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584

In [21]:
df.groupby("Crop_Year")["Production"].mean()

Crop_Year
1997-01-01    1.484637e+07
1998-01-01    1.217970e+07
1999-01-01    1.315389e+07
2000-01-01    1.238662e+07
2001-01-01    1.241942e+07
2002-01-01    1.522620e+07
2003-01-01    1.537292e+07
2004-01-01    1.755663e+07
2005-01-01    1.843552e+07
2006-01-01    1.907980e+07
2007-01-01    1.747728e+07
2008-01-01    1.908592e+07
2009-01-01    1.919557e+07
2010-01-01    1.391461e+07
2011-01-01    2.123497e+07
2012-01-01    1.457579e+07
2013-01-01    1.745928e+07
2014-01-01    1.837206e+07
2015-01-01    1.836603e+07
2016-01-01    1.578889e+07
2017-01-01    1.483537e+07
2018-01-01    1.687104e+07
2019-01-01    1.693476e+07
2020-01-01    2.750602e+05
Name: Production, dtype: float64

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [23]:
df["Crop_Encoded"] = le.fit_transform(df["Crop"])

In [24]:
df[["Crop", "Crop_Encoded"]].head()

           Crop  Crop_Encoded
0      Arecanut             0
1     Arhar/Tur             1
2   Castor seed             8
3      Coconut              9
4  Cotton(lint)            11

In [25]:
df_encoded = pd.get_dummies(df, columns=["Season"])

In [26]:
df_encoded.head()

,Crop,Crop_Year,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Crop_Encoded,Season_Autumn,Season_Kharif,Season_Rabi,Season_Summer,Season_Whole Year,Season_Winter
0,Arecanut,1997-01-01,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255,0,False,False,False,False,True,False
1,Arhar/Tur,1997-01-01,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891,1,False,True,False,False,False,False
2,Castor seed,1997-01-01,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638,8,False,True,False,False,False,False
3,Coconut,1997-01-01,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,9,False,False,False,False,True,False
4,Cotton(lint),1997-01-01,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584,11,False,True,False,False,False,False

In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
oe=OrdinalEncoder()
df["State_Encoded"]=oe.fit_transform(df[["Production_per_Area"]])
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Crop_Encoded,State_Encoded
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255,0,6158.0
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891,1,5514.0
2,Castor seed,1997-01-01,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638,8,12.0
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,9,17821.0
4,Cotton(lint),1997-01-01,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584,11,2837.0

In [32]:
numeric_df = df.select_dtypes(include="number")

In [33]:
result2 = pd.DataFrame({
    "Minimum": numeric_df.min(),
    "Maximum": numeric_df.max(),
    "Range": numeric_df.max() - numeric_df.min()
})

result2

                     Minimum       Maximum         Range
Area                    0.50  5.080810e+07  5.080810e+07
Production              0.00  6.326000e+09  6.326000e+09
Annual_Rainfall       301.30  6.552700e+03  6.251400e+03
Fertilizer             54.17  4.835407e+09  4.835407e+09
Pesticide               0.09  1.575051e+07  1.575051e+07
Yield                   0.00  2.110500e+04  2.110500e+04
Production_per_Area     0.00  2.110500e+04  2.110500e+04
Crop_Encoded            0.00  5.400000e+01  5.400000e+01
State_Encoded           0.00  1.795000e+04  1.795000e+04

In [34]:
result3= pd.DataFrame({
    "Q1 (25%)": numeric_df.quantile(0.25),
    "Q2 (Median)": numeric_df.quantile(0.50),
    "Q3 (75%)": numeric_df.quantile(0.75)
})

In [35]:
result3["IOR"] = result3["Q3 (75%)"] - result3["Q1 (25%)"]
print(result3)

                         Q1 (25%)   Q2 (Median)      Q3 (75%)           IOR
Area                   1390.00000  9.317000e+03  7.511200e+04  7.372200e+04
Production             1393.00000  1.380400e+04  1.227180e+05  1.213250e+05
Annual_Rainfall         940.70000  1.247600e+03  1.643700e+03  7.030000e+02
Fertilizer           188014.62000  1.234957e+06  1.000385e+07  9.815833e+06
Pesticide               356.70000  2.421900e+03  2.004170e+04  1.968500e+04
Yield                     0.60000  1.030000e+00  2.388889e+00  1.788889e+00
Production_per_Area       0.59585  1.035673e+00  2.463386e+00  1.867536e+00
Crop_Encoded             17.00000  3.100000e+01  4.300000e+01  2.600000e+01
State_Encoded          4373.00000  8.641000e+03  1.322600e+04  8.853000e+03

In [36]:
result4 =pd.DataFrame({
    "skewness": numeric_df.skew()
})
print(result4.round(3))

                     skewness
Area                   21.858
Production             19.299
Annual_Rainfall         2.132
Fertilizer             13.413
Pesticide              25.636
Yield                  12.785
Production_per_Area    12.808
Crop_Encoded           -0.222
State_Encoded           0.038